# Workflow para construir y desplegar un sitio Jekyll en GitHub Pages
name: Desplegar Jekyll en GitHub Pages con dependencias preinstaladas

on:
  # Ejecuta en cada push a la rama principal
  push:
    branches: ["Inicio"]  # Cambia 'Inicio' a la rama que deseas usar
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Trabajo para construir el sitio Jekyll
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Instalar dependencias Jekyll
        run: |
          bundle install

      - name: Construir el sitio con Jekyll
        run: |
          bundle exec jekyll build --config _config.yml  # Asegura que use el archivo _config.yml
        env:
          JEKYLL_ENV: production

      - name: Subir artefacto de la página construida
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site  # Directorio donde Jekyll genera el sitio

  # Trabajo para desplegar el sitio en GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
